### ISSUE TITLE
Please issue new release (0.6.7)

### ISSUE THREAD

**Issue by tillea** [biod/sambamba#281]
Hi,
I intend to package sambamba for Debian.  Unfortunately there is some problem with std.stream in undeaD for the latest release (see thread on [Debian Med packaging list](https://lists.alioth.debian.org/pipermail/debian-med-packaging/2017-March/051054.html) )  Matthias Klumpp has given a hint that this is fixed in sambamba Git - so a release of the recent code would help.
Kind regards, Andreas.

**Comment by pjotrp** [comment]
Hi Andreas! A Debian release would be very useful and I want to help. I work on Debian with GNU Guix.
 
In the git master there is a Makefile.guix without rdmd that we can use/adapt for Debian. Can you take a look? What version of ldc2/ldmd2 compiler are you actually using?

**Comment by lomereiter** [comment]
Hello Andreas,
Thanks for working on this! I've just pushed v0.6.6 tag.

Please note `sambamba-ldmd2-64` goal doesn't require rdmd, and it's the one we use for release builds.

**Comment by tillea** [comment]
Hi Pjotr,
On Sun, Mar 05, 2017 at 03:12:29AM -0800, Pjotr Prins wrote:
> Hi Andreas! A Debian release would be very useful and I want to help. I work on Debian with GNU Guix.
Just for the sake of interest: What's the advantage of Guix over plain Debian?  Specifically when working in bioinformatix I'd recommend to use the work of Debian Med packaging team directly - but may be I'm missing something.
  
> In the git master there is a Makefile.guix without rdmd that we can use/adapt for Debian. Can you take a look? What version of ldc2/ldmd2 compiler are you actually using?
Enabling build without rdmd is helpful

    $ ldc2 --version
    LDC - the LLVM D compiler (1.1.0):
      based on DMD v2.071.2 and LLVM 3.8.1
      built with LDC - the LLVM D compiler (1.0.0)
      Default target: x86_64-pc-linux-gnu
      Host CPU: haswell
      http://dlang.org - http://wiki.dlang.org/LDC
    
When trying to build with Makefile.guix I get

    Makefile.guix:60: recipe for target 'utils/strip_bcf_header.o' failed
    make[2]: *** [utils/strip_bcf_header.o] Error 1
    sambamba/slice.d(106): Error: undead.stream.Stream at /usr/include/d/undead/stream.d(390) conflicts with std.stream.Stream at /usr/lib/ldc/x86_64-linux-gnu/include/d/std/stream.d(390)
    sambamba/slice.d(176): Error: undead.stream.Stream at /usr/include/d/undead/stream.d(390) conflicts with std.stream.Stream at /usr/lib/ldc/x86_64-linux-gnu/include/d/std/stream.d(390)
    sambamba/slice.d(197): Error: undead.stream.Stream at /usr/include/d/undead/stream.d(390) conflicts with std.stream.Stream at /usr/lib/ldc/x86_64-linux-gnu/include/d/std/stream.d(390)
    Makefile.guix:60: recipe for target 'main.o' failed

Kind regards

    Andreas.
    
-- 
http://fam-tille.de

**Comment by tillea** [comment]
Hi Artem,
On Sun, Mar 05, 2017 at 03:49:07AM -0800, Artem Tarasov wrote:
> Thanks for working on this! I've just pushed v0.6.6 tag.
Thanks a lot for you both very quick and helpful responses.
 
> Please note `sambamba-ldmd2-64` goal doesn't require rdmd, and it's the one we use for release builds. 
Looks promising.  The general problem is that you are trusting on git submodules while the Debian build needs to use the packaged version of what you are assuming in subdirectories of your build root.  This requires editing of makefiles and resource files.  I'll keep you updated once I'm through this and if I might need further help.
Kind regards, Andreas.

**Comment by pjotrp** [comment]
Hi Andreas, I am very busy this week, but I'll try to help. 

GNU Guix solves a lot of things that Debian does not do. I use it for a massive deployment of a software stack. Depends a bit on the use case, but I see it used when people need full control of software dependency graph. Another thing is that it is distribution agnostic and many HPC environments run ancient versions of Linux. Guix can be great for that. Essentially I use Debian for the basics and Guix packages on top for the specializations.

**Comment by pjotrp** [comment]
We should be heading for a new release.

**Comment by pjotrp** [comment]
Released.
